# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3HFjpz11hRqw-VC22K9KZpkj_5g5xoz
"""



"""# Theory Part


# 1. What is Simple Linear Regression?
Simple Linear Regression is a statistical method that models the relationship between two continuous variables by fitting a linear equation (Y = mX + c) to observed data. One variable is the independent predictor (X), and the other is the dependent response (Y).

# 2. What are the key assumptions of Simple Linear Regression?
Linearity: Relationship between X and Y is linear.

Independence: Observations are independent.

Homoscedasticity: Constant variance of errors.

Normality: Errors are normally distributed.

No multicollinearity (only one predictor, so not an issue here).

# 3. What does the coefficient m represent in the equation Y = mX + c?
It represents the slope of the line—i.e., the change in Y for a one-unit change in X.

# 4. What does the intercept c represent in the equation Y = mX + c?
It is the value of Y when X = 0; the point where the line crosses the Y-axis.

# 5. How do we calculate the slope m in Simple Linear Regression?
𝑚
=
𝑛
∑
𝑋
𝑌
−
∑
𝑋
∑
𝑌
𝑛
∑
𝑋
2
−
(
∑
𝑋
)
2
m=
n∑X
2
 −(∑X)
2

n∑XY−∑X∑Y
​

This is derived from minimizing the squared errors (least squares method).

# 6. What is the purpose of the least squares method in Simple Linear Regression?
To find the best-fitting line by minimizing the sum of squared residuals between observed and predicted values.

# 7. How is the coefficient of determination (R²) interpreted in Simple Linear Regression?
R² measures the proportion of variance in the dependent variable explained by the independent variable. Value ranges from 0 to 1.

# 8. What is Multiple Linear Regression?
A statistical technique to model the relationship between one dependent variable and two or more independent variables.

# 9. What is the main difference between Simple and Multiple Linear Regression?
Simple uses one predictor; Multiple uses two or more.

# 10. What are the key assumptions of Multiple Linear Regression?
Linearity

Independence of errors

Homoscedasticity

Normality of errors

No multicollinearity among predictors

# 11. What is heteroscedasticity, and how does it affect results?
It means the variance of residuals is not constant. It can lead to inefficient estimates and biased standard errors.

# 12. How can you improve a Multiple Linear Regression model with high multicollinearity?
Remove or combine correlated variables.

Use PCA (Principal Component Analysis).

Apply Ridge or Lasso Regression.

# 13. Common techniques for transforming categorical variables?
One-hot encoding

Label encoding

Dummy variables

# 14. What is the role of interaction terms?
They capture the combined effect of two variables on the outcome, especially when the effect of one variable depends on the level of another.

# 15. How can the interpretation of intercept differ?
In simple regression, the intercept is the expected Y when X = 0. In multiple regression, it's the expected Y when all Xs = 0, which may not be meaningful depending on the data context.

# 16. What is the significance of the slope in regression?
It indicates how much the dependent variable is expected to change with a unit change in the predictor.

# 17. How does the intercept provide context?
It sets the baseline value of the dependent variable when all predictors are zero, giving context to the slope.

# 18. Limitations of using R² alone?
Doesn’t account for number of predictors.

Can be high even if model is overfitting.

Doesn’t measure prediction accuracy.

# 19. How to interpret a large standard error for a coefficient?
It suggests the coefficient is unstable or unreliable, possibly due to high variance or multicollinearity.

# 20. How to identify heteroscedasticity in residual plots?
Look for a funnel shape or pattern in residuals vs. predicted values plot. Addressing it is crucial for valid inference.

# 21. High R² but low adjusted R²—what does it mean?
Likely indicates that some predictors do not add value to the model and may be overfitting.

# 22. Why scale variables in Multiple Linear Regression?
To ensure equal influence and interpretability, especially important in regularization techniques.

#23. What is Polynomial Regression?
An extension of linear regression where the relationship between X and Y is modeled as an nth-degree polynomial.

# 24. How does it differ from linear regression?
Linear uses straight-line relationships; polynomial uses curved (nonlinear) relationships.

# 25. When is Polynomial Regression used?
When the data shows a nonlinear pattern that a straight line can't capture.

# 26. General equation for Polynomial Regression?
𝑌
=
𝑏
0
+
𝑏
1
𝑋
+
𝑏
2
𝑋
2
+
𝑏
3
𝑋
3
+
…
+
𝑏
𝑛
𝑋
𝑛
Y=b
0
​
 +b
1
​
 X+b
2
​
 X
2
 +b
3
​
 X
3
 +…+b
n
​
 X
n

# 27. Can Polynomial Regression be applied to multiple variables?
Yes, by including polynomial terms for each variable and their interactions.

# 28. Limitations of Polynomial Regression?
Risk of overfitting

Poor extrapolation

High variance with increasing degree

# 29. Methods to evaluate model fit for polynomial degree?
Cross-validation

Adjusted R²

AIC/BIC

Visualization of residuals

# 30. Why is visualization important?
To understand model fit, detect overfitting or underfitting, and communicate insights clearly.

# 31. How is Polynomial Regression implemented in Python?
Using scikit-learn:


from sklearn.preprocessing import PolynomialFeatures

from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline

model = make_pipeline(PolynomialFeatures(degree=2), LinearRegression())
model.fit(X_train, y_train)

"""